/*
 * This file is part of Just Enough HarvestCraft.
 *
 * Just Enough HarvestCraft is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Just Enough HarvestCraft is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Just Enough HarvestCraft.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.pearx.jehc;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.Logger;

import java.util.Collections;

@Mod(name = Jehc.NAME, modid = Jehc.MODID, version = Jehc.VERSION, acceptedMinecraftVersions = Jehc.ACCEPTED_MINECRAFT_VERSIONS, dependencies = Jehc.DEPENDENCIES, clientSideOnly = true)
@SideOnly(Side.CLIENT)
public class Jehc {
    @Mod.Instance
    public static Jehc INSTANCE;

    public static final String NAME = "Just Enough HarvestCraft";
    public static final String MODID = "jehc";
    public static final String VERSION = "";
    public static final String DESCRIPTION = "";
    public static final String ACCEPTED_MINECRAFT_VERSIONS = "";
    public static final String DEPENDENCIES = "";

    private Logger log;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        log = e.getModLog();
        setupMetadata(e.getModMetadata());
    }

    private void setupMetadata(ModMetadata d) {
        d.autogenerated = false;
        d.authorList = Collections.singletonList("mrapplexz");
        d.description = DESCRIPTION;
        d.version = VERSION;
        d.modId = MODID;
        d.name = NAME;
        d.logoFile = "logo.png";
        d.url = "https://www.curseforge.com/minecraft/mc-mods/just-enough-harvestcraft";
    }

    public Logger getLog() {
        return log;
    }
}
