package ru.pearx.jehc;

import mezz.jei.api.IGuiHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.Logger;

import java.util.Arrays;

/*
 * Created by mrAppleXZ on 20.05.17 15:54.
 */
@Mod(name = JEHC.NAME, modid = JEHC.MODID, version = JEHC.VERSION, acceptedMinecraftVersions = "", dependencies = "", clientSideOnly = true)
@SideOnly(Side.CLIENT)
public class JEHC
{
    @Mod.Instance
    public static JEHC INSTANCE;


    public static final String NAME = "Just Enough HarvestCraft";
    public static final String MODID = "jehc";
    public static final String VERSION = "@VERSION@";

    private Logger log;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e)
    {
        log = e.getModLog();
        setupMetadata(e.getModMetadata());
    }

    private void setupMetadata(ModMetadata d)
    {
        d.autogenerated = false;
        d.authorList = Arrays.asList("mrAppleXZ");
        d.description = "JEI integration for Pam's HarvestCraft.";
        d.version  = VERSION;
        d.modId = MODID;
        d.name = NAME;
    }

    public Logger getLog()
    {
        return log;
    }
}
