package ru.pearx.jehc;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.Logger;

import java.util.Collections;

/*
 * Created by mrAppleXZ on 20.05.17 15:54.
 */
@Mod(name = Jehc.NAME, modid = Jehc.MODID, version = Jehc.VERSION, acceptedMinecraftVersions = Jehc.ACCEPTED_MINECRAFT_VERSIONS, dependencies = Jehc.DEPENDENCIES, clientSideOnly = true)
@SideOnly(Side.CLIENT)
public class Jehc
{
    @Mod.Instance
    public static Jehc INSTANCE;


    public static final String NAME = "Just Enough HarvestCraft";
    public static final String MODID = "jehc";
    public static final String VERSION = "";
    public static final String DESCRIPTION = "";
    public static final String ACCEPTED_MINECRAFT_VERSIONS = "";
    public static final String DEPENDENCIES = "";


    private Logger log;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e)
    {
        log = e.getModLog();
        setupMetadata(e.getModMetadata());
    }

    private void setupMetadata(ModMetadata d)
    {
        d.autogenerated = false;
        d.authorList = Collections.singletonList("mrAppleXZ");
        d.description = DESCRIPTION;
        d.version  = VERSION;
        d.modId = MODID;
        d.name = NAME;
    }

    public Logger getLog()
    {
        return log;
    }
}
