package ru.pearx.jehc;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.versioning.ArtifactVersion;
import net.minecraftforge.fml.common.versioning.DefaultArtifactVersion;
import net.minecraftforge.fml.common.versioning.VersionRange;

import java.util.Arrays;

/**
 * Created by mrAppleXZ on 20.05.17 15:54.
 */
@Mod(modid = JEHC.MODID, name = JEHC.NAME, version = JEHC.VERSION, acceptedMinecraftVersions = "[1.11,1.11.2]")
public class JEHC
{
    public static final String NAME = "Just Enough HarvestCraft";
    public static final String MODID = "jehc";
    public static final String VERSION = "1.2.0";

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e)
    {
        setupMetadata(e.getModMetadata());
    }

    private void setupMetadata(ModMetadata d)
    {
        d.autogenerated = false;
        d.authorList = Arrays.asList("mrAppleXZ");
        d.dependencies = Arrays.asList(new DefaultArtifactVersion("jei", "[4.3,)"), new DefaultArtifactVersion("harvestcraft", "[1.11.2,)"));
        d.description = "JEI integration for Pam's HarvestCraft.";
        d.version  = VERSION;
        d.modId = MODID;
        d.name = NAME;
    }
}
